### ISSUE TITLE
1-tuples

### ISSUE THREAD

**Issue by opensdh** [steve-downey/papers#4]
Only with a certain interpretation of "tuple" can the _n_-ary Cartesian product [be interpreted](https://en.wikipedia.org/wiki/Cartesian_product#n-ary_Cartesian_product) as repeated application of the binary one.  That interpretation has the advantage, for our purposes, that the Cartesian product of 1 set _must_ be interpreted as _P_<sub>0</sub>&times;_X_<sub>1</sub> in order to promote _X_<sub>1</sub> to pairs {(_x_<sub>1,_i_</sub>,&empty;)}<sub>_i_</sub>.  (Wikipedia does not mention this special case.)

However, it's not the C++ interpretation of `tuple`, and the binary operation we're really generalizing is something like `std::tuple_cat` with every explicit argument lifted to a range of tuples.  This is the only way that `views::single(std::tuple<>())` can be an _identity_ for the operation, and it's the same sense in which `views::repeat(std::tuple<>())` can be an identity for `zip`.  It might be better overall to just appeal to the fact that the Cartesian product, commuted with cardinality, becomes the ordinary product, and to provide examples like the two 0-relations to explain the value of it.  Surely there also should be examples of algorithms that produce a (vacuous) useful case with 0 ranges.

**Comment by steve-downey** [comment]
I went the other direction with this in the paper, where `std::tuple<A, std::tuple<B, C>>` , `std::tuple<std::tuple<A, B>, C>` and `std::tuple<A, B, C>` are all isomorphic, which also side-steps which direction the fold of cartesian product is running. It's well justified in algebraic type theory, at least. 

I don't think we're going to get much push back on the empty product for cartesian_product. It's going to be explaining why trying to extend it to other product-ish things like zip leads to contradictions. Of course, that's based on feedback from people generally in favor. 

Sorry for not getting back faster. My apologies. Looks like this also is getting pushed back a week in LEWG which means possibly seeing in SG first. By a whole day.
